;; -*- mode: eask; lexical-binding: t -*-

(package "cursor-preview"
         "0.1.1"
         "Preview cursor movement while execute command interactively")

(website-url "https://github.com/jcs-elpa/cursor-preview")
(keywords "convenience" "interactive" "preview" "cursor" "movement" "display")

(package-file "cursor-preview.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "24.3")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
